#:schema node_modules/wrangler/config-schema.json
name = "filter-website"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

# Custom domain routing
routes = [
  { pattern = "filter.coffee", custom_domain = true },
  { pattern = "www.filter.coffee", custom_domain = true }
]
